# Site
repository: phkh1366/Pegah-Hashemvand
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pegah Hashemvand Khiabani (Ph.D.)
title: Geospatial and earth observation researcher
email: pegah_hk@restec.or.jp,  phkh1366@iis.u-tokyo.ac.jp 
website: www.github.com/phkh1366

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: p66_hashemvand
github_username:  phkh1366
# stackoverflow_username: "00000001"
# facebook_username: jekyll
instagram_username: p66_hashemvand
linkedin_username: p.hashemvand@gmail.com
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# About Section
# about_title: About Me
about_profile_image: IMG_3744.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pegah Hashemvand Khiabani. My specialty is spaceborne and airborne data analytics. 
  I'm particularly interested in the application of remote sensing in agriculture and the enviroment.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Remote Sensing Technology Center of Japan, Tokyo, Japan
        link: https://www.restec.or.jp/en/index.html
        link_text: RESTEC
        sub_title: Geospatial and earth observation researcher at Solution service Dept.II
        caption: April 2020 - Present
        description: | # this will include new lines to allow paragraphs
           RESTEC aims to contribute to national and international communities and to the lives of the people by utilizing its remote sensing technologies in a wide range of areas, including the agriculture, forestry, and fishery industries, environment, disaster prevention, map information, and education.
    
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Carbon Capital Advisors, Tokyo, Japan
        link: https://carboncapitaladvisors.com/
        link_text: Carbon Capital Advisors
        sub_title: Geospatial and earth observation Consultant
        caption: September 2019 - November 2019
        description: | # this will include new lines to allow paragraphs
           Project: Smart Cookstove Project. 
           A show case of how Internet of Things (IoT) and satellite imagery data can be coupled with blockchain verification methods to create levels of transparency and trust in carbon market.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ph.D., The Uninversity of Tokyo, Japan
        caption: September 2016 - September 2019
        sub_title: Civil Engineering (Remote Sensing)
        link: http://wtlab.iis.u-tokyo.ac.jp/en/index_e.html
        link_text: Remote sensing of environment and disaster Lab. 
        quote: >
          Title: Biogeophysical modeling of oil palm yield in Malaysia and Indonesia 
        description: | # this will include new lines to allow paragraphs
            Elaeis guineensis known as oil palm is extensively cultivated in South-East Asia, especially in Indonesia and Malaysia. Due to the significant revenue of this industry, this sector plays a crucial role in the national development of Indonesia and Malaysia. However, expansion and intensification of this industry have not been robustly managed and caused a range of significant negative impacts. Apart from the challenges caused by this industry, the most crucial technical challenge of this sector is that its actual yields per unit of area are well below potential levels and have stagnated over the last two decades. Narrowing this gap is the only path that ensures this industry’s prosperity as it increases the revenue without compromising its environmental impacts. 
            To close the existing gap, key causes and the magnitude of the gap need to be addressed. Potential and actual yields are two main components of yield gap assessment. Estimation of potential yield is the most critical part of the yield gap assessment. So far, a limited number of attempts have been made to model oil palm potential yield. However, as oil palm is extended in a considerable spatial and temporal heterogeneous area, estimated potential yields through existing models do not represent an entire country and are not consider a full range of conditions. Also, the majority of the existing models are demanding in terms of vegetation measurement data. While remote sensing-based yield simulation models can complement traditional site-specific models due to their unbeatable spatial and temporal coverage. 
            Although so far spaceborne and airborne remote sensing have been used to extract required information for oil palm potential and actual yields estimation, yet there is no attempt integrating remote sensing data to model oil palm yields for yield gap assessment. 
            Therefore, the objective of this study was to develop a model and methodology to assess oil palm potential and actual yields using publicly available remote sensing data and platforms in Indonesia and Malaysia. Leveraging spatial-temporal coverage of remote sensing data, this research was able to test this hypothesis that Malaysia and Indonesia have developed different trajectory of land use to satisfy the global demand in which Malaysia has more invested on narrowing yield gap through intensification while Indonesia has been more in favor of land expansion.
  
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: M.Sc., The Uninversity of Tehran, Iran
        caption: September 2011 - February 2014
        sub_title: Agricultural Engineering (Soil’s genesis, taxonomy and land suitability assessment)
        link: https://aet.ut.ac.ir/en
        link_text: Faculty of Agricultural Engineering & Technology
        quote: >
          Title: Ghazvin’s land suitability assessment using GIS based multi-criteria approach for major crops. 
#         description: | # this will include new lines to allow paragraphs
  - title:  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc., The Uninversity of Tehran, Iran
        caption: September 2006 - September 2010
        sub_title: Agricultural Engineering (Soil’s genesis, taxonomy and land suitability assessment)
        link: https://aet.ut.ac.ir/en
        link_text: Faculty of Agricultural Engineering & Technology
#         quote: >
#           Title: Ghazvin’s land suitability assessment using GIS based multi-criteria approach for major crops. 
#         description: | # this will include new lines to allow paragraphs


  - title: Main Poblications
    layout: text
    content: | # this will include new lines to allow paragraphs
     Peer-reviewed Articles
        - Hashemvand P. & Takeuchi W. (2020) [Assessment of oil palm yield and biophysical suitability in Indonesia and Malaysia](https://drive.google.com/file/d/1yLd4zU93WyjQaXKEoDOx2AWwHvqfPkDv/view?usp=sharing), International Journal of Remote Sensing, 41:22, 8520-8546, DOI: 10.1080/01431161.2020.1782503
        - Hashemvand Khiabani P., Takeuchi W. (2020) [Supporting Oil Palm Replanting Programs Using UAV and GIS in Malaysia](https://drive.google.com/file/d/1_jvCa73IZ3A3DyxAEn3SEIwGTMya4Lyz/view?usp=sharing). In: Avtar R., Watanabe T. (eds) Unmanned Aerial Vehicle: Applications in Agriculture and Environment. Springer, Cham. https://doi.org/10.1007/978-3-030-27157-2_6
     Conference Papers
        - Hashemvand P., Takeuchi W., 2019. Assessment of biophysical suitability of oil palm and its actual yield in Malaysian oil palm plantations. International Symposium on Remote Sensing 2019 (ISRS), T aipei, T aiwan, 2019/4/17; Oral presentation.
        - Hashemvand P., Takeuchi W., 2019. Assessing Oil Palm Yield Gap at The Location of Malaysian and Indonesian exciting Plantations from Perspective of Bio-Physical Suitability. 第27回 生研フォーラム「宇宙からの地球環境・災 害のモニタリングとリスク評価」:東京大学生産技術研究所 (東京都目黒区); 2019/3/6; Poster.
        - Hashemvand P., Takeuchi W., 2018. Mapping oil palm expansion from 2000 to 2017 in Indonesia and Malaysia. 39th Asian Conference on Remote Sensing (ACRS), Kuala Lumpur, Malaysia. 2018/10/15; Oral presentation.
        - Hashemvand P., Takeuchi W., 2018. Oil palm bio-physical suitability assessment in Indonesia and Malaysia over 2007-2017. 9th International Conference and Exhibition on Geospatial & Remote Sensing (IGRSM). Kuala Lumpur, Malaysia, 2018/4/25; Oral presentation.
        - Hashemvand P., Takeuchi W., 2018. Impact of el Nino-southern oscillation (ENSO) on Oil palm bio-physical Suitability in Indonesia and Malaysia. 第 26回 生研フォーラム「宇宙からの地球環境・災害のモニタリングとリスク評 価」:東京大学生産技術研究所 (東京都目黒区), 2018/3/6; Poster.
        - Hashemvand P., Takeuchi W., 2017. Automated oil palm crown detection using unmanned aerial vehicle imagery in Malaysia. 38th Asian Conference on Remote Sensing: Delhi, India. 2017/08/24; Oral presentation.



      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
